# Generated by Django 3.2.14 on 2022-07-25 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('mem_id', models.AutoField(primary_key=True, serialize=False)),
                ('mem_userid', models.CharField(max_length=255)),
                ('mem_password', models.CharField(max_length=255)),
                ('mem_username', models.CharField(max_length=255)),
                ('mem_nickname', models.CharField(max_length=255)),
                ('mem_email', models.CharField(max_length=255)),
                ('mem_profile_content', models.CharField(max_length=255)),
                ('mem_receive_mail', models.CharField(max_length=255)),
                ('mem_on_activate', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_category', models.CharField(max_length=255)),
                ('post_tag', models.CharField(max_length=255)),
                ('post_title', models.CharField(max_length=255)),
                ('post_content', models.CharField(max_length=255)),
                ('post_datetime', models.DateTimeField(auto_now_add=True)),
                ('post_related_link', models.CharField(max_length=255)),
                ('post_hit', models.IntegerField()),
                ('post_userid', models.ForeignKey(db_column='post_userid', on_delete=django.db.models.deletion.CASCADE, related_name='post', to='board.member')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rtn_id', models.AutoField(primary_key=True, serialize=False)),
                ('rtn_design', models.IntegerField()),
                ('rtn_trend', models.IntegerField()),
                ('rtn_usability', models.IntegerField()),
                ('rtn_tech', models.IntegerField()),
                ('rtn_contents', models.IntegerField()),
                ('rtn_post_id', models.ForeignKey(db_column='rtn_post_id', on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='board.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostFile',
            fields=[
                ('pfi_id', models.AutoField(primary_key=True, serialize=False)),
                ('pfi_origin_name', models.CharField(max_length=255)),
                ('pfi_file_name', models.CharField(max_length=255)),
                ('pfi_type', models.CharField(max_length=255)),
                ('pfi_route', models.CharField(max_length=255)),
                ('pfi_filesize', models.IntegerField()),
                ('pfi_post_id', models.ForeignKey(db_column='pfi_post_id', on_delete=django.db.models.deletion.CASCADE, related_name='post_file', to='board.post')),
            ],
        ),
        migrations.CreateModel(
            name='MemberUid',
            fields=[
                ('uid_id', models.AutoField(primary_key=True, serialize=False)),
                ('uid_social_type', models.CharField(max_length=255)),
                ('uid_mem_id', models.ForeignKey(db_column='uid_mem_id', on_delete=django.db.models.deletion.CASCADE, related_name='uid', to='board.member')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cmt_id', models.AutoField(primary_key=True, serialize=False)),
                ('cmt_content', models.CharField(max_length=255)),
                ('cmt_datetime', models.DateTimeField(auto_now_add=True)),
                ('cmt_mem_id', models.ForeignKey(db_column='cmt_mem_id', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='board.member')),
                ('cmt_post_id', models.ForeignKey(db_column='cmt_post_id', on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='board.post')),
            ],
        ),
    ]
